version: '3.8'

services:
  app:
    container_name: planit_app
    build: ./app
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - ${APP_PORT}:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL
    stdin_open: true

  api:
    container_name: planit_api
    build: ./api
    volumes:
      - './api:/api'
    ports:
      - ${API_PORT}:5000
    depends_on:
      - postgres
    restart: "always"
    environment:
      - API_PORT
      - FLASK_DEBUG=1
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD=development_password

  postgres:
    container_name: planit_postgres
    image: postgres:14.0
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD=development_password
    ports:
      - "5432:5432"
    volumes:
      - planit-postgres-data:/var/lib/postgresql/data

volumes:
  planit-postgres-data:
    name: planit-postgres-data